### ISSUE TITLE
SSL Certificates

### ISSUE THREAD

**Issue by alexander-petkov** [alexander-petkov/wfas#12]
Update security SSL certificates on Rackspace with new ones (see Bryce's email). The current certificate is set to expire in Aug. 

Configure the Geoserver cluster on Plume to use certificates as well.

**Comment by alexander-petkov** [comment]
I updated SSL Certificates on Apache and Tomcat, as they were set to expire today. 
I am closing this ticket for now.
In case there are any problems, please let me know  and re-open this ticket.

**Comment by alexander-petkov** [comment]
Also, I set Tomcat to redirect all requests to https. Please let me know if there are any issues with this.

**Comment by wmjolly** [comment]
Did you get the certificates from Bryce?

**Comment by alexander-petkov** [comment]
> Did you get the certificates from Bryce?
Yes, the new certificates issued from GoDaddy
