### ISSUE TITLE
Calculate local time for weatherstream data

### ISSUE THREAD

**Issue by alexander-petkov** [alexander-petkov/wfas#25]
Observed, as well as forecast data from RTMA, NDFD, and GFS archives carries UTC timestamps. 

Convert timestamps from UTC to local time. This is required by Flammap, which is used to ingest Weatherstream (wxs) data.

**Comment by alexander-petkov** [comment]
Weather stream data is extracted based on user input geographic coordinates. 
These coordinates will be used for time zone lookup, and convert UTC timestamps to the appropriate time zone .

**Comment by alexander-petkov** [comment]
Timezone lookup will be based on the latest released time zone boundaries from this project:

https://github.com/evansiroky/timezone-boundary-builder/releases/tag/2019b

Thankfully, the data is, for the most part, static.

**Comment by alexander-petkov** [comment]
[This commit ](https://github.com/alexander-petkov/wfas/commit/986b1b2b643e222d19969d83b3a9b7fdfd49a262) has the above changes required above. 

The lookup is based on determining the appropriate time zone from the user input coordinates. 

Right now the timezone is configured as a vector layer in Geoserver--I may inlcude the shapefile in the JAR archive, in effort to reduce the requirement for the layer to be configured in Geoserver. 

The code for the weather stream WPS also went some restructuring changes, so it is easier to read.

**Comment by wmjolly** [comment]
Very cool solution Alex. Strong work.
