### ISSUE TITLE
Configure and use Ceph for data storage

### ISSUE THREAD

**Issue by alexander-petkov** [alexander-petkov/wfas#4]

**Comment by alexander-petkov** [comment]
Update the Ceph cluster to 10 GigE. 

Research performance improvement, particularly reading from ceph mounted pools. 

Paper:
https://www.exertishammer.com/assets/uploads/resources/Samsung%20-%20White%20Paper%20-%20High-Performance%20Red%20Hat%20Ceph%20Storage%20Using%20Samsung%20NVMe%20SSDs.pdf

**Comment by wmjolly** [comment]
How much storage would we need for this current effort?  I could buy enough
NVM's to RAID up and make this thign fast.

**Comment by alexander-petkov** [comment]
Good question...  A few Terabytes at least...

The Ceph nodes are 24 drives each. Let's see how things improve with
10 GigE cards

**Comment by wmjolly** [comment]
I think we could do 4 2TB NVM drives in JBOD config. Or at least a set of
SSD working discs for these machines. Could speed things up a lot.

**Comment by alexander-petkov** [comment]
Ceph performance tuning checklist:

https://accelazh.github.io/ceph/Ceph-Performance-Tuning-Checklist

**Comment by alexander-petkov** [comment]
> I think we could do 4 2TB NVM drives in JBOD config. Or at least a set of SSD working discs for these machines. Could speed things up a lot. 

I believe this is a good idea, and worth implementing. I researched if a separate Ceph pool can be created, targeting specific disks, or specific kind of disks (hdd or ssd): 

https://stackoverflow.com/questions/58060333/ceph-how-to-place-a-pool-on-specific-osd

Furthermore, currently there are 4 2TB older HDDs on ceph-0. They can be replaced with SSD drives.

**Comment by alexander-petkov** [comment]
SSD drives are installed in ceph-0 and configured as Ceph OSDs. 

I created a SSD-only pool, and ran some benchmarking:
[rados_bench.txt](https://github.com/alexander-petkov/wfas/files/3976594/rados_bench.txt)

wfas_data is the SSD pool, cephfs_data is hdd pool.

Max and Min bandwidth/sec fields in the summary for each test are indicative of performance, although the rest of the test is interesting as well

**Comment by wmjolly** [comment]
Holy moly!  What a difference.....

**Comment by alexander-petkov** [comment]
Network appears to be the current bottleneck. 

Here are some performance results under different scenarios:

1. VM-mounted Ceph filesystem (our use-case scenario):
 * Writing:
```bash
sudo dd if=/dev/urandom of=/mnt/cephfs/tmp/largefile bs=1M count=1024
1024+0 records in
1024+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 6.35076 s, 169 MB/s

sudo dd if=/dev/urandom of=/mnt/rbd/largefile bs=1M count=1024
1024+0 records in
1024+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 5.72587 s, 188 MB/s
```
* Reading:

```bash
time dd if=/mnt/cephfs/tmp/largefile of=/dev/null bs=8k
131072+0 records in
131072+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 9.66039 s, 111 MB/s

real    0m9.699s
user    0m0.048s
sys     0m0.542s
echo 3 | sudo tee /proc/sys/vm/drop_caches

time dd if=/mnt/rbd/largefile of=/dev/null bs=8k
131072+0 records in
131072+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 9.78859 s, 110 MB/s

real    0m9.812s
user    0m0.051s
sys     0m0.535s
```

2. Directly on the ceph host:
* Writing:
```bash
sudo dd if=/dev/urandom of=/mnt/wfas_cephfs/largefile bs=1M count=1024
1024+0 records in
1024+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 5.48896 s, 196 MB/s

sudo dd if=/dev/urandom of=/mnt/cephfs/tmp/largefile bs=1M count=1024
1024+0 records in
1024+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 5.75937 s, 186 MB/s
```
* Reading:
```bash
time dd if=/mnt/wfas_cephfs/largefile of=/dev/null bs=8k
131072+0 records in
131072+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 1.13718 s, 944 MB/s

real    0m1.155s
user    0m0.109s
sys     0m0.506

time dd if=/mnt/cephfs/tmp/largefile of=/dev/null bs=8k
131072+0 records in
131072+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 4.8981 s, 219 MB/s

real    0m4.927s
user    0m0.067s
sys     0m0.482s
```
