### ISSUE TITLE
Investigate ncWMS, in particular GetTimeSeries operation

### ISSUE THREAD

**Issue by alexander-petkov** [alexander-petkov/wfas#5]

**Comment by alexander-petkov** [comment]
ncWMS GetCapabilities

[GetCapabilities](https://www.wfas.net:8443/geoserver/ows?service=wms&version=1.3.0&request=GetCapabilities&dataset=wfas) on a namespace works as per the documentation

**Comment by alexander-petkov** [comment]
Example [GetTimeSeries](https://www.wfas.net:8443/geoserver/wms?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetTimeSeries&FORMAT=image%2Fjpeg&TIME=2019-05-25T11:00:00.000Z/2019-05-25T23:00:00.000Z&QUERY_LAYERS=wfas:Dewpoint_temperature_height_above_ground&STYLES&LAYERS=wfas:Dewpoint_temperature_height_above_ground&INFO_FORMAT=image%2Fpng&FEATURE_COUNT=50&X=50&Y=50&SRS=EPSG%3A45558&WIDTH=101&HEIGHT=101&BBOX=3.724365234375%2C40.81420898437501%2C5.943603515625%2C43.03344726562501) request, which returns a chart

**Comment by alexander-petkov** [comment]
This raises the question: Is it possible to build a chart that aggregates multiple coverages, for different time extents?  Perhaps this task is a WPS candidate.

**Comment by alexander-petkov** [comment]
Interesting, this [GetTimeSeries](https://www.wfas.net:8443/geoserver/wms?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetTimeSeries&FORMAT=image%2Fjpeg&TIME=2019-05-25T11:00:00.000Z/2019-05-25T23:00:00.000Z&QUERY_LAYERS=wfas:Dewpoint_temperature_height_above_ground&STYLES&LAYERS=wfas:Dewpoint_temperature_height_above_ground&INFO_FORMAT=text%2Fcsv&FEATURE_COUNT=50&X=50&Y=50&SRS=EPSG%3A45558&WIDTH=101&HEIGHT=101&BBOX=3.724365234375%2C40.81420898437501%2C4.724365234375%2C41.81420898437501) request returns a CSV, with only 1 point (which is a corner in the BBOX parameter) specified as XY. So, are all BBOX GetTimeSeries requests single point queries?

```
# X: 41.31915947942451
# Y: 4.2194147393254955
Time (UTC),wfas:Dewpoint_temperature_height_above_ground
2019-05-25T11:00:00.000Z,297.07000732421875
2019-05-25T12:00:00.000Z,297.260009765625
2019-05-25T13:00:00.000Z,297.3999938964844
2019-05-25T14:00:00.000Z,297.3299865722656
2019-05-25T15:00:00.000Z,297.2300109863281
2019-05-25T16:00:00.000Z,297.1000061035156
2019-05-25T17:00:00.000Z,297.3299865722656
2019-05-25T18:00:00.000Z,297.3800048828125
2019-05-25T19:00:00.000Z,297.5799865722656
2019-05-25T20:00:00.000Z,297.489990234375
2019-05-25T21:00:00.000Z,297.7300109863281
2019-05-25T22:00:00.000Z,297.8399963378906
2019-05-25T23:00:00.000Z,298.05999755859375
```

**Comment by alexander-petkov** [comment]
NcWMS GetTimeSeries request will return data for one coverage at a time:

```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><!DOCTYPE ServiceExceptionReport SYSTEM "http://localhost/geoserver/schemas/wms/1.1.1/WMS_exception_1_1_1.dtd"> <ServiceExceptionReport version="1.1.1" >   <ServiceException>
      The QUERY_LAYERS parameter must specify a single coverage layer for the GetTimeSeries operation
</ServiceException></ServiceExceptionReport>
```
Looks like I am looking at creating a custom solution for merging/concatenating multiple CSV files. 
A frontend application using Javascript comes to mind. Probably the same client that can provide Landfire raster data.

**Comment by wmjolly** [comment]
Yeah, kinda figured that would happen. Could a WPS work for this request?

**Comment by alexander-petkov** [comment]
> Yeah, kinda figured that would happen. Could a WPS work for this request?

I started looking at designing and writing a custom WPS process for our needs.
