### ISSUE TITLE
Configure a multi-dimensional coverage in Geoserver

### ISSUE THREAD

**Issue by alexander-petkov** [alexander-petkov/wfas#9]
Configure a multi-dimensional coverage (with time) in Geoserver. The RTMA data is a perfect candidate for this.

**Comment by alexander-petkov** [comment]
Getting started

https://geoserver.geo-solutions.it/edu/en/multidim/index.html

**Comment by wmjolly** [comment]
Man, that's a really useful tutorial for GeoServer and it is perfect fo the RTMA.

**Comment by alexander-petkov** [comment]
I managed to get something going... Here is 1 day of RTMA data configured as an ImageMosaic Coverage store. The layer described is Dewpoint temperature:

`<wcs:CoverageOfferingBrief><wcs:description>Generated from ImageMosaic</wcs:description><wcs:name>wfas:Dewpoint_temperature_height_above_ground</wcs:name><wcs:label>Dewpoint_temperature_height_above_ground</wcs:label><wcs:lonLatEnvelope srsName="urn:ogc:def:crs:OGC:1.3:CRS84"><gml:pos>-138.39411566911662 19.33471943329413</gml:pos><gml:pos>-59.021498911360425 57.2405538861492</gml:pos><gml:timePosition>2019-05-25T11:00:00.000Z</gml:timePosition><gml:timePosition>2019-05-25T23:00:00.000Z</gml:timePosition></wcs:lonLatEnvelope><wcs:keywords><wcs:keyword>Dewpoint_temperature_height_above_ground</wcs:keyword><wcs:keyword>WCS</wcs:keyword><wcs:keyword>ImageMosaic</wcs:keyword></wcs:keywords></wcs:CoverageOfferingBrief>`

Sample request:

`https://www.wfas.net:8443/geoserver/wfas/wms?service=WMS&version=1.1.0&request=GetMap&layers=wfas%3ADewpoint_temperature_height_above_ground&bbox=-3272417.06827313%2C-265067.458838747%2C2683186.35538251%2C3790837.96665125&width=768&height=523&srs=EPSG%3A45558&format=application/openlayers&TIME=2019-05-25T14:00:00Z`

The hour value for TIME parameter can be changed b/n 11 and 23

**Comment by alexander-petkov** [comment]
Wiki should follow.

The work over the last two days with the ImageMosaic plugin raises some questions and concerns:

1. Are the input files required to carry an appropriate file extension? This need testing--in my effort to successfully create an ImageMosaic coverage, I renamed the Grib files with a .grb2 extension

2. The mosaic needs to be updated daily. Is this feasible with the ImageMosaic extension? The process of creating a coverage generates grib-related cached data (.gbx9 and ncx3 files), which will need to be cleaned every time (once a day) a 14-day archive is refreshed with a wget command. 

I was hoping for a simple wget sync and updating the relevant index (postgis tables in this case).

3. Can the mosaic be updated via the REST interface?

**Comment by alexander-petkov** [comment]
These are the .properties and XML settings I got to work. 

It is possible to subset only desired variables from the archives, here only 2 coverages are listed.

datastore.properties:
```
SPI=org.geotools.data.postgis.PostgisNGDataStoreFactory
host=somehost
port=someport
database=somedb
schema=someschema
user=someuser
Loose\ bbox=true
Estimated\ extends=false
validate\ connections=true
Connection\ timeout=10
preparedStatements=true
```
indexer.properties:
```
Schema=*the_geom:Polygon,location:String,imageindex:Integer,time:java.util.Date
TimeAttribute=GRIB_REF_TIME
Caching=false
AbsolutePath=true
Levels=2539.702999999999975,2539.702999999999975
LevelsNum=1
LocationAttribute=location
```


indexer.xml:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Indexer>
    <domains>
        <domain name="time">
            <attributes>
                <attribute>time</attribute>
            </attributes>
        </domain>
    </domains>
    <schemas>
        <schema name="default">
            <attributes>the_geom:Polygon,location:String,imageindex:Integer,time:java.util.Date</attributes>
        </schema>
    </schemas>
    <coverages>
        <coverage>
            <name>Dewpoint_temperature_height_above_ground</name>
            <schema ref="default"/>
            <domains>
                <domain ref="time"/>
            </domains>
        </coverage>
        <coverage>
            <name>Temperature_height_above_ground</name>
            <schema ref="default"/>
            <domains>
                <domain ref="time"/>
            </domains>
        </coverage>
    </coverages>
    <parameters>
        <parameter name="AuxiliaryFile" value="rtma.xml"/>
        <parameter name="AbsolutePath" value="true"/>
        <parameter name="uniqueTimeAttribute" value="true"/>
    </parameters>
</Indexer>
```
rtma.xml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Indexer>
    <coverages>
        <coverage>
            <name>Dewpoint_temperature_height_above_ground</name>
        </coverage>
        <coverage>
            <name>Temperature_height_above_ground</name>
        </coverage>
    </coverages>
    <parameters>
        <parameter name="uniqueTimeAttribute" value="true"/>
    </parameters>
</Indexer>
```

**Comment by wmjolly** [comment]
> Wiki page on this topic should follow.
> 
> The work over the last two days with the ImageMosaic plugin raises some questions and concerns:
> 
> 1. Are the input files required to carry an appropriate file extension? This need testing--in my effort to successfully create an ImageMosaic coverage, I renamed the Grib files with a .grb2 extension, but I am not clear that it was necessary. I really want to keep orig data as is.
> 2. The mosaic needs to be updated (at least) daily. Is this feasible with the ImageMosaic extension? The process of creating a coverage generates grib-related cached data (.gbx9 and .ncx3 files), which will need to be cleaned every time (once a day at a minimum) a 14-day archive is refreshed with a wget command.
> 
> I was hoping for a simple wget sync and updating the relevant index (postgis tables in this case).
> 
> 1. Can the mosaic be updated via the REST interface?
> 
> More ImageMosaic experimenting awaits.

**Comment by wmjolly** [comment]
Sorry for accidentally closing this issue.  I hope I reopened it correctly.  Anyway, I know that we can use the REST service to update the ImageMosaic. I think I have an example somewhere.  I love what you've done so far and I think it's putting us on a good track already.  I am pretty sure that the GetTimeSeries only works for a point.  We can use WCS requests in the future.  I found a solution that can clip data data and return as NetCDF files and it worked pretty well. As far as variables, we'll need 2m air temperature, 2m dewpoint temperature, windspeed, wind direction and we'll have to find the best source for precipitation data.  Also, we'll have to use the 2m temperature and dewpoint to derive relative humidity.  I have something that does that right now.

**Comment by wmjolly** [comment]
I found this in my notes.  It has some great info about re-indexing an ImageMosaic data store.
http://osgeo-org.1560.x6.nabble.com/Reload-ImageMosaic-store-via-Rest-API-td5269099.html

**Comment by alexander-petkov** [comment]
Geosolutions.it guide on configuring and updating Imagemosaic coverage through REST API:

[Manage ImageMosaic content through REST API](https://geoserver.geo-solutions.it/edu/en/multidim/rest/index.html)

**Comment by alexander-petkov** [comment]
Getting a list of granules for a multidimensional coverage via REST:

```http
http://192.168.59.56:8081/geoserver/rest/workspaces/landfire/coveragestores/rtma_mosaic/coverages/Dewpoint_temperature_height_above_ground/index/granules.xml
```

**Comment by alexander-petkov** [comment]
Deleting a specific granule from a coverage via REST:

```console
curl -v -u uname:passwd -XDELETE http://localhost:8081/geoserver/rest/workspaces/landfire/coveragestores/rtma_mosaic/coverages/Dewpoint_temperature_height_above_ground/index/granules/Dewpoint_temperature_height_above_ground.236
```

What bothers me about this: granules are deleted on per coverage (variable) basis. 
I much preffer to delete a granule from a coveragestore, and consequently from all coverages associated with it with one command.

**Comment by alexander-petkov** [comment]
Adding a granule via REST:

```console
curl -v -u uname:passwd -XPOST -H "Content-type: text/plain" -d "file:///mnt/cephfs/wfas/data/rtma/met/grib/rtma2p5.20190610/rtma2p5.t11z.2dvaranl_ndfd.grb2_wexp" "http://localhost:8081/geoserver/rest/workspaces/landfire/coveragestores/rtma_mosaic/external.imagemosaic"
```
This request adds the granule to the coveragestore, and **_all coverages_** derived from it. Much more elegant than deleting granules as described in the previous comment.

**Comment by alexander-petkov** [comment]
Algorithm for forecast data archive update:

1. Update archive from ftp. 
2. Add new granules to mosaic. 
3. Remove granules from mosaic no longer on the FTP archive (or simply more than 14 days old?)
4. Remove old files from system.

**Comment by alexander-petkov** [comment]
[This comment](https://github.com/alexander-petkov/wfas/issues/10#issuecomment-505898609) links to a source which updates the currently configured RTMA coveragestore. 

Only Dewpoint and Temperature height are currently configured. 

**To do:**
I need to add the rest of the variables needed to the Mosaic from these Grib files.

**Comment by alexander-petkov** [comment]
Issues #10, #11, #13, and #14 implement the solutions here
